/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObjectsTypeIdRouteImport } from './routes/objects/$type.$id'
import { Route as ApiPublicHooksEvaluateAssetRisksRouteImport } from './routes/api/public/hooks/evaluate-asset-risks'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsTypeIdRoute = ObjectsTypeIdRouteImport.update({
  id: '/objects/$type/$id',
  path: '/objects/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEvaluateAssetRisksRoute =
  ApiPublicHooksEvaluateAssetRisksRouteImport.update({
    id: '/api/public/hooks/evaluate-asset-risks',
    path: '/api/public/hooks/evaluate-asset-risks',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/objects/$type/$id': typeof ObjectsTypeIdRoute
  '/api/public/hooks/evaluate-asset-risks': typeof ApiPublicHooksEvaluateAssetRisksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/objects/$type/$id': typeof ObjectsTypeIdRoute
  '/api/public/hooks/evaluate-asset-risks': typeof ApiPublicHooksEvaluateAssetRisksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/objects/$type/$id': typeof ObjectsTypeIdRoute
  '/api/public/hooks/evaluate-asset-risks': typeof ApiPublicHooksEvaluateAssetRisksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/objects/$type/$id'
    | '/api/public/hooks/evaluate-asset-risks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/objects/$type/$id'
    | '/api/public/hooks/evaluate-asset-risks'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/objects/$type/$id'
    | '/api/public/hooks/evaluate-asset-risks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ObjectsTypeIdRoute: typeof ObjectsTypeIdRoute
  ApiPublicHooksEvaluateAssetRisksRoute: typeof ApiPublicHooksEvaluateAssetRisksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$type/$id': {
      id: '/objects/$type/$id'
      path: '/objects/$type/$id'
      fullPath: '/objects/$type/$id'
      preLoaderRoute: typeof ObjectsTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/evaluate-asset-risks': {
      id: '/api/public/hooks/evaluate-asset-risks'
      path: '/api/public/hooks/evaluate-asset-risks'
      fullPath: '/api/public/hooks/evaluate-asset-risks'
      preLoaderRoute: typeof ApiPublicHooksEvaluateAssetRisksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ObjectsTypeIdRoute: ObjectsTypeIdRoute,
  ApiPublicHooksEvaluateAssetRisksRoute: ApiPublicHooksEvaluateAssetRisksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
